version: '3.3'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql8-container
    environment:
      MYSQL_ROOT_PASSWORD: 8878332#
      MYSQL_DATABASE: backend
      MYSQL_USER: adminroot
      MYSQL_PASSWORD: 8878332#
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: